export const registerFormControls = [
  {
    name: "userName",
    label: "User Name",
    placeholder: "Enter your user name",
    componentType: "input",
    type: "text",
  },
  {
    name: "email",
    label: "Email",
    placeholder: "Enter your email",
    componentType: "input",
    type: "email",
  },
  {
    name: "password",
    label: "Password",
    placeholder: "Enter your password",
    componentType: "input",
    type: "password",
  },
];

export const loginFormControls = [
  {
    name: "email",
    label: "Email",
    placeholder: "Enter your email",
    componentType: "input",
    type: "email",
  },
  {
    name: "password",
    label: "Password",
    placeholder: "Enter your password",
    componentType: "input",
    type: "password",
  },
];

export const addProductFormElements = [
  {
    label: "Title",
    name: "title",
    componentType: "input",
    type: "text",
    placeholder: "Enter product title",
  },
  {
    label: "Description",
    name: "description",
    componentType: "textarea",
    placeholder: "Enter product description",
  },
  {
    label: "Category",
    name: "category",
    componentType: "select",
    options: [
      { id: "mobileAccessories", label: "Mobile Accessories" },
      { id: "personalCare", label: "Personal Care Appliances" },
      { id: "smartDevices", label: "Smart Devices" },
      { id: "tvAudioVideo", label: "TV, Audio & Video Players" },
      { id: "storagePeripherals", label: "Storage and Peripherals" },
      { id: "homeKitchenAccessories", label: "Home & Kitchen Accessories" },
      { id: "computerComponents", label: "Computer - Accessories and Components" },
      { id: "homeDecor", label: "Home Decor" },
      { id: "travelProducts", label: "Leather & Travel Products" },
      { id: "jewellery", label: "Jewellery" },
    ],
  },
  {
    label: "Sub Category",
    name: "subCategory",
    componentType: "select",
    options: [
      { id: "air_coolers", label: "Air Coolers" },
      { id: "audio_players", label: "Audio Players" },
      { id: "batteries", label: "Batteries" },
      { id: "battery_chargers", label: "Battery Chargers" },
      { id: "bluetooth", label: "Bluetooth" },
      { id: "bracelet", label: "Bracelet" },
      { id: "bracelet_for_man", label: "Bracelet for Man" },
      { id: "bracelet_for_woman", label: "Bracelet for Woman" },
      { id: "cabinets", label: "Cabinets" },
      { id: "cable_power_meter", label: "Cable & Power Meter" },
      { id: "cable_protector", label: "Cable Protector" },
      { id: "camera_mobile_mods", label: "Camera Mobile Mods" },
      { id: "car_chargers", label: "Car Chargers" },
      { id: "cases_covers", label: "Cases & Covers" },
      { id: "charger", label: "Charger" },
      { id: "charging_pad", label: "Charging Pad" },
      { id: "cleaning_kit", label: "Cleaning Kit" },
      { id: "data_cables", label: "Data Cables" },
      { id: "digital_pen", label: "Digital Pen" },
      { id: "earphone_cable_organizer", label: "Earphone Cable Organizer" },
      { id: "emergency_lights", label: "Emergency Lights" },
      { id: "fans", label: "Fans" },
      { id: "flash", label: "Flash" },
      { id: "graphics_tablets", label: "Graphics Tablets" },
      { id: "hair_dryers", label: "Hair Dryers" },
      { id: "hand_blender", label: "Hand Blender" },
      { id: "hand_juicer", label: "Hand Juicer" },
      { id: "headphone_amplifiers", label: "Headphone Amplifiers" },
      { id: "headphone_stand", label: "Headphone Stand" },
      { id: "headphones", label: "Headphones" },
      { id: "irons", label: "Irons" },
      { id: "key_holder", label: "Key Holder" },
      { id: "keyboard_skin", label: "Keyboard Skin" },
      { id: "keyboards", label: "Keyboards" },
      { id: "laptop_accessories_combo", label: "Laptop Accessories Combo" },
      { id: "laptop_stand", label: "Laptop Stand" },
      { id: "membrane", label: "Membrane" },
      { id: "memory_card", label: "Memory Card" },
      { id: "microphone_accessories", label: "Microphone Accessories" },
      { id: "microphones", label: "Microphones" },
      { id: "mobile_accessories_combo", label: "Mobile Accessories Combo" },
      { id: "mobile_battery", label: "Mobile Battery" },
      { id: "mobile_camera_lens_protector", label: "Mobile Camera Lens Protector" },
      { id: "mobile_holder", label: "Mobile Holder" },
      { id: "mobile_phone_lens", label: "Mobile Phone Lens" },
      { id: "mobile_skins", label: "Mobile Skins" },
      { id: "mobile_spare_parts", label: "Mobile Spare Parts" },
      { id: "mouse", label: "Mouse" },
      { id: "mousepads", label: "Mousepads" },
      { id: "multipurpose_controllers", label: "Multipurpose Controllers" },
      { id: "otg_adapter", label: "OTG Adapter" },
      { id: "otg_cable", label: "OTG Cable" },
      { id: "pen_drives", label: "Pen Drives" },
      { id: "perfume_bottles", label: "Perfume Bottles" },
      { id: "perfume_spray_nozzle", label: "Perfume Spray Nozzle" },
      { id: "power_banks", label: "Power Banks" },
      { id: "projector_screen", label: "Projector Screen" },
      { id: "rat_trap", label: "Rat Trap" },
      { id: "remote", label: "Remote" },
      { id: "room_heater", label: "Room Heater" },
      { id: "routers", label: "Routers" },
      { id: "safety_lock_straps", label: "Safety Lock Straps" },
      { id: "sat_phone_converter", label: "Sat Phone Converter" },
      { id: "screen_guards", label: "Screen Guards" },
      { id: "security_lock", label: "Security Lock" },
      { id: "selfie_stick", label: "Selfie Stick" },
      { id: "sensor_security_system", label: "Sensor Security System" },
      { id: "sewing_machines", label: "Sewing Machines" },
      { id: "sim_sd_card_tray", label: "Sim & SD Card Tray" },
      { id: "smart_assistant", label: "Smart Assistant" },
      { id: "smart_door_lock", label: "Smart Door Lock" },
      { id: "smart_gloves", label: "Smart Gloves" },
      { id: "smart_lighting", label: "Smart Lighting" },
      { id: "smart_pen", label: "Smart Pen" },
      { id: "smart_switches", label: "Smart Switches" },
      { id: "smart_watches", label: "Smart Watches" },
      { id: "sound_bar", label: "Sound Bar" },
      { id: "speaker_mobile", label: "Speaker Mobile" },
      { id: "speaker_mount", label: "Speaker Mount" },
      { id: "speakers", label: "Speakers" },
      { id: "surge_protector", label: "Surge Protector" },
      { id: "table_clocks", label: "Table Clocks" },
      { id: "table_lamp", label: "Table Lamp" },
      { id: "torch", label: "Torch" },
      { id: "touch_keyboard", label: "Touch Keyboard" },
      { id: "touchpad", label: "Touchpad" },
      { id: "trimmer", label: "Trimmer" },
      { id: "tube_light", label: "Tube Light" },
      { id: "usb_adaptor", label: "USB Adaptor" },
      { id: "usb_gadget", label: "USB Gadget" },
      { id: "vacuum_cleaners", label: "Vacuum Cleaners" },
      { id: "video_players", label: "Video Players" },
      { id: "wall_clocks", label: "Wall Clocks" },
      { id: "wall_lamps", label: "Wall Lamps" },
      { id: "wallet_card_wallets", label: "Wallet Card Wallets" },
      { id: "water_dispensers", label: "Water Dispensers" },
      { id: "watch_straps", label: "Watch Straps" },
      { id: "watches", label: "Watches" },
      { id: "webcams", label: "Webcams" },
      { id: "wrist_bands", label: "Wrist Bands" },
      { id: "wrist_rest", label: "Wrist Rest" }

    ],
  },
  {
    label: "Brand",
    name: "brand",
    componentType: "select",
    options: [
      { id: "zbi", label: "ZBI" },
      { id: "ubon", label: "UBON" },
      { id: "vingajoy", label: "Vingajoy" },
      { id: "ulove", label: "ULove" },
      { id: "others", label: "Others" },

      // { id: "zara", label: "Zara" },
      // { id: "h&m", label: "H&M" },
    ],
  },
  {
    label: "Price",
    name: "price",
    componentType: "input",
    type: "number",
    placeholder: "Enter product price",
  },
  {
    label: "Sale Price",
    name: "salePrice",
    componentType: "input",
    type: "number",
    placeholder: "Enter sale price",
  },
  {
    label: "Total Stock",
    name: "totalStock",
    componentType: "input",
    type: "number",
    placeholder: "Enter total stock",
  },
];

//this is the shopping view header menu that wil show on the shop page
export const shoppingViewHeaderMenuItems = [
  {
    id: "home",
    label: "Home",
    path: "/shop/home",
  },
  {
    id: "products",
    label: "Products",
    path: "/shop/listing",
  },
  {
    id: "mobileAccessories",
    label: "Mobile Accessories",
    path: "/shop/listing",
  },
  {
    id: "computerComponents",
    label: "Computer Accessories",
    path: "/shop/listing",
  },
  {
    id: "smartDevices",
    label: "Smart Devices",
    path: "/shop/listing",
  },
  {
    id: "personalCare",
    label: "Personal Care",
    path: "/shop/listing",
  },
  {
    id: "storagePeripherals",
    label: "Storage Peripherals",
    path: "/shop/listing",
  },
  {
    id: "search",
    label: "Search",
    path: "/shop/search",
  },
];

export const categoryOptionsMap = {
  mobileAccessories: "Mobile Accessories",
  personalCare: "Personal Care",
  smartDevices: "Smart Devices",
  tvAudioVideo: "TV, Audio & Video Players",
  storagePeripherals: "Storage and Peripherals",
  homeKitchenAccessories: "Home & Kitchen Accessories",
  computerComponents: "Computer Accessories",
  homeDecor: "Home Decor",
  travelProducts: "Leather & Travel Products",
  jewellery: "Jewellery"
};

export const brandOptionsMap = {
  zbi: "ZBI",
  ubon: "UBON",
  vingajoy: "Vingajoy",
  ulove: "ULove",
  others: "Others",
};

export const filterOptions = {
  category: [
    { id: "mobileAccessories", label: "Mobile Accessories" },
    { id: "personalCare", label: "Personal Care" },
    { id: "smartDevices", label: "Smart Devices" },
    { id: "tvAudioVideo", label: "TV, Audio & Video Players" },
    { id: "storagePeripherals", label: "Storage and Peripherals" },
    { id: "homeKitchenAccessories", label: "Home & Kitchen Accessories" },
    { id: "computerComponents", label: "Computer Accessories" },
    { id: "homeDecor", label: "Home Decor" },
    { id: "travelProducts", label: "Leather & Travel Products" },
    { id: "jewellery", label: "Jewellery" },
  ],
  brand: [
    { id: "zbi", label: "ZBI" },
    { id: "ubon", label: "UBON" },
    { id: "vingajoy", label: "Vingajoy" },
    { id: "ulove", label: "ULove" },
    { id: "others", label: "Others" },

  ],
};

export const sortOptions = [
  { id: "price-lowtohigh", label: "Price: Low to High" },
  { id: "price-hightolow", label: "Price: High to Low" },
  { id: "title-atoz", label: "Title: A to Z" },
  { id: "title-ztoa", label: "Title: Z to A" },
];

export const addressFormControls = [
  {
    label: "Address",
    name: "address",
    componentType: "input",
    type: "text",
    placeholder: "Enter your address",
  },
  {
    label: "City",
    name: "city",
    componentType: "input",
    type: "text",
    placeholder: "Enter your city",
  },
  {
    label: "Pincode",
    name: "pincode",
    componentType: "input",
    type: "text",
    placeholder: "Enter your pincode",
  },
  {
    label: "Phone",
    name: "phone",
    componentType: "input",
    type: "text",
    placeholder: "Enter your phone number",
  },
  {
    label: "Notes",
    name: "notes",
    componentType: "textarea",
    placeholder: "Enter any additional notes",
  },
];